### ISSUE TITLE
Error when trying to play sound when timer finish

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-skill-alerts#8]
```
2024-01-04 23:06:40.220 - OVOS - ovos_skill_alerts.util.alert_manager:rm_alert:597 - INFO - Removing PENDING TIMER: one minute timer (4d9cd03d-ccc6-4e59-9277-ccd36bf4a3fb)
2024-01-04 23:06:43.304 - ovos-skill-alerts.openvoiceos - ERROR - Skill ovos-skill-alerts.openvoiceos resource 'beep4.mp3' for lang 'en-us' not found in skill
2024-01-04 23:06:43.313 - OVOS - ovos_skill_alerts:timer_sound_file:174 - WARNING - Could not resolve requested file: beep4.mp3
2024-01-04 23:06:43.329 - OVOS - ovos_utils.events:wrapper:118 - ERROR - cannot access local variable 'steps' where it is not associated with a value
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 116, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/util/alert_manager.py", line 710, in _handle_alert_expiration
    self._callback_expiration(alert_cpy)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1787, in _alert_expired
    self._play_notify_expired(alert)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1851, in _play_notify_expired
    if escalate and secs_played % steps == 0 \
                                  ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
2024-01-04 23:06:43.353 - OVOS - ovos_utils.events:on_error:291 - ERROR - An error occurred executing the scheduled event: cannot access local variable 'steps' where it is not associated with a value
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 116, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/util/alert_manager.py", line 710, in _handle_alert_expiration
    self._callback_expiration(alert_cpy)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1787, in _alert_expired
    self._play_notify_expired(alert)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1851, in _play_notify_expired
    if escalate and secs_played % steps == 0 \
                                  ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
```

**Comment by goldyfruit** [comment]
Fix the sound file doesn't fix the issue.

```
2024-01-04 23:10:46.069 - OVOS - ovos_skill_alerts.util.alert_manager:rm_alert:597 - INFO - Removing PENDING TIMER: one minute timer (d5fb28a8-c15f-4207-b9e2-615e50310e6b)
2024-01-04 23:10:49.159 - ovos-skill-alerts.openvoiceos - ERROR - Skill ovos-skill-alerts.openvoiceos resource 'default-timer.wav' for lang 'en-us' not found in skill
2024-01-04 23:10:49.165 - OVOS - ovos_skill_alerts:timer_sound_file:174 - WARNING - Could not resolve requested file: default-timer.wav
2024-01-04 23:10:49.210 - OVOS - ovos_utils.events:wrapper:118 - ERROR - cannot access local variable 'steps' where it is not associated with a value
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 116, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/util/alert_manager.py", line 710, in _handle_alert_expiration
    self._callback_expiration(alert_cpy)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1787, in _alert_expired
    self._play_notify_expired(alert)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1851, in _play_notify_expired
    if escalate and secs_played % steps == 0 \
                                  ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
2024-01-04 23:10:49.219 - OVOS - ovos_utils.events:on_error:291 - ERROR - An error occurred executing the scheduled event: cannot access local variable 'steps' where it is not associated with a value
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/events.py", line 116, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/util/alert_manager.py", line 710, in _handle_alert_expiration
    self._callback_expiration(alert_cpy)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1787, in _alert_expired
    self._play_notify_expired(alert)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_skill_alerts/__init__.py", line 1851, in _play_notify_expired
    if escalate and secs_played % steps == 0 \
                                  ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
```

**Comment by goldyfruit** [comment]
The `steps`  issue might be related to the fact that this skill is running on a HiveMind cluster, not sure from where the `mycroft.volume.get` message is collected.

**Comment by emphasize** [comment]
thanks, i haven't set a default when the config value `escalate_volume` was set to `False`

**Comment by emphasize** [comment]
The correct use in a hivemind (multiroom) setup we have to figure out, as this is not straight forward and multiple ways to set up.
By now everything is coming from the skill device
